workflows:
  ios-build:
    name: iOS Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      vars:
        XCODE_PROJECT: "stremioios.xcodeproj"  # Correctly indented key-value pair
        XCODE_SCHEME: "stremioios"  # Correctly indented key-value pair
        NODE_VERSION: "14.x"  # Correctly indented key-value pair
    scripts:
      - name: Install dependencies
        script: |
          brew install cocoapods
          pod install
      - name: Build iOS app
        script: |
          xcodebuild -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME" -sdk iphoneos
